/**
 * @author B. Alfanous
 * 
 * CENG 320 Lab 04
 */
import java.io.*;
import java.net.*;
import java.util.*;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GUIBlackJack extends javax.swing.JFrame {
    ArrayList hand = new ArrayList<Card>();
     Socket socket=null;
     ObjectOutputStream out=null;
     ObjectInputStream remoteInput = null;
    String message;
    String machineName = "127.0.0.1";
    int port = 40048;
    
       
    Object card = "";
    Card cards = new Card();
    String choice = "";
    /**
     * Creates new form GUIBlackJack
     */
    public GUIBlackJack() throws IOException {
        initComponents();
        try {
	    socket = new Socket(InetAddress.getByName(machineName), port);
            out = new ObjectOutputStream(socket.getOutputStream());
	} catch (IOException e) {
	   // System.out.println("Could not send to " + machineName + ":" + port);
	    e.printStackTrace();
	    System.exit(-1);
	}
        catch(Exception e) {
         //  System.out.println("Generic exception");
           e.printStackTrace();
         }
          // System.out.println("Remote host: munro.humber.ca Port: 40048" );
          txtIPAddress.setText(socket.getRemoteSocketAddress().toString());
          txtPort.setText("40048");
        BufferedReader localInput = new BufferedReader(new InputStreamReader(System.in));  
	remoteInput = new ObjectInputStream(socket.getInputStream());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        stayButton = new javax.swing.JButton();
        shuffleButton = new javax.swing.JButton();
        messageLable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardDisplayTXT = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        portLable = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        newGameBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Black Jack Client");

        dealButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dealButton.setText("Deal");
        dealButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dealButtonMouseClicked(evt);
            }
        });

        showButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        showButton.setText("Show");
        showButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showButtonMouseClicked(evt);
            }
        });

        stayButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        stayButton.setText("Stay");
        stayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stayButtonMouseClicked(evt);
            }
        });
        stayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayButtonActionPerformed(evt);
            }
        });

        shuffleButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        shuffleButton.setText("Shuffle");
        shuffleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shuffleButtonMouseClicked(evt);
            }
        });

        messageLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        messageLable.setText("Message:");

        cardDisplayTXT.setColumns(20);
        cardDisplayTXT.setRows(5);
        jScrollPane1.setViewportView(cardDisplayTXT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Message From:");

        txtIPAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });

        portLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        portLable.setText("Port:");

        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        newGameBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        newGameBtn.setText("New Game");
        newGameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(stayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(shuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(messageLable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(portLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(portLable)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(messageLable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void dealButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealButtonMouseClicked
        try {
            // TODO add your handling code here:
            card = remoteInput.readObject();
            hand.add((Card)card);
        } catch (IOException ex) {
            Logger.getLogger(GUIBlackJack.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIBlackJack.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dealButtonMouseClicked

    private void showButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showButtonMouseClicked
        // TODO add your handling code here:
        cardDisplayTXT.setText(Arrays.toString(hand.toArray()));
    }//GEN-LAST:event_showButtonMouseClicked

    private void stayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stayButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stayButtonMouseClicked

    private void shuffleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shuffleButtonMouseClicked
        // TODO add your handling code here:
        Collections.shuffle(hand);
    }//GEN-LAST:event_shuffleButtonMouseClicked

    private void newGameBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newGameBtnMouseClicked

    private void stayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayButtonActionPerformed
        try {
            // TODO add your handling code here:
            out.writeObject(hand);
        } catch (IOException ex) {
            Logger.getLogger(GUIBlackJack.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_stayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUIBlackJack().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUIBlackJack.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
        
        
        
        
        
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cardDisplayTXT;
    private javax.swing.JButton dealButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLable;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JLabel portLable;
    private javax.swing.JButton showButton;
    private javax.swing.JButton shuffleButton;
    private javax.swing.JButton stayButton;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
